[package]
name = "dd-gui"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
glium = "0.16.0"
glutin = "0.7.0"
winit = "0.5.11"
cgmath = "0.14.1"

[lib]
name = "dd_gui"

[[example]]
name = "basic"
